-- Migração Supabase: Morte -> Baixa + status ABATIDO
-- Execute no SQL Editor do Supabase.

BEGIN;

-- 1) Renomeia tabela antiga para baixa_log, cobrindo cenários legado.
DO $$
BEGIN
  IF to_regclass('public.baixa_log') IS NULL AND to_regclass('public.morte_log') IS NOT NULL THEN
    ALTER TABLE public.morte_log RENAME TO baixa_log;
  ELSIF to_regclass('public.baixa_log') IS NULL AND to_regclass('public.morte') IS NOT NULL THEN
    ALTER TABLE public.morte RENAME TO baixa_log;
  END IF;
END
$$;

-- 2) Garante existência da tabela baixa_log no formato atual.
CREATE TABLE IF NOT EXISTS public.baixa_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nascimento_id bigint NOT NULL,
  tipo_baixa text NOT NULL DEFAULT 'MORTE',
  data_morte text NOT NULL,
  fazenda text NOT NULL,
  foto1 text,
  foto2 text,
  foto3 text,
  audio text,
  descricao text,
  location_cidade text,
  location_bairro text,
  location_latitude double precision,
  location_longitude double precision,
  usuario_id bigint NOT NULL,
  criado_em text NOT NULL,
  atualizado_em text NOT NULL
);

-- 3) Garante colunas novas e constraints em baixa_log.
ALTER TABLE public.baixa_log
  ADD COLUMN IF NOT EXISTS tipo_baixa text;

UPDATE public.baixa_log
SET tipo_baixa = 'MORTE'
WHERE tipo_baixa IS NULL OR btrim(tipo_baixa) = '';

ALTER TABLE public.baixa_log
  ALTER COLUMN tipo_baixa SET NOT NULL;

ALTER TABLE public.baixa_log
  ALTER COLUMN tipo_baixa SET DEFAULT 'MORTE';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'baixa_log_tipo_baixa_check'
      AND conrelid = 'public.baixa_log'::regclass
  ) THEN
    ALTER TABLE public.baixa_log
      ADD CONSTRAINT baixa_log_tipo_baixa_check
      CHECK (upper(btrim(tipo_baixa)) IN ('MORTE', 'ABATE'));
  END IF;
END
$$;

UPDATE public.baixa_log
SET tipo_baixa = upper(btrim(tipo_baixa));

-- 4) Garante status ABATIDO na tabela animal.
UPDATE public.animal
SET status = 'ATIVO'
WHERE status IS NULL OR btrim(status) = '';

UPDATE public.animal
SET status = upper(btrim(status));

DO $$
DECLARE
  c record;
BEGIN
  FOR c IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.animal'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%status%'
  LOOP
    EXECUTE format('ALTER TABLE public.animal DROP CONSTRAINT %I', c.conname);
  END LOOP;

  ALTER TABLE public.animal
    ADD CONSTRAINT animal_status_check
    CHECK (status IN ('ATIVO','VENDIDO','MORTO','ABATIDO'));
END
$$;

-- 5) Índices úteis para sync/listagem.
CREATE INDEX IF NOT EXISTS idx_baixa_log_usuario_id ON public.baixa_log (usuario_id);
CREATE INDEX IF NOT EXISTS idx_baixa_log_nascimento_id ON public.baixa_log (nascimento_id);
CREATE INDEX IF NOT EXISTS idx_baixa_log_atualizado_em ON public.baixa_log (atualizado_em);

COMMIT;
